### ISSUE TITLE
schedules in redis gets cleared immediately after set

### ISSUE THREAD

**Issue by vikramcp** [moove-it/sidekiq-scheduler#101]
Hi,

I am using sidekiq-scheduler and noticed a strange behaviour in web UI. the schedules were only visible for every alternative sidekiq process restarts. so if its visible for the 1st time then i would have to restart the process 2 more times to see the schedules in web UI again. The culprit seems be the following line : 

https://github.com/moove-it/sidekiq-scheduler/blob/master/lib/sidekiq-scheduler/schedule.rb#L46

def schedule=(schedule_hash)
      schedule_hash = prepare_schedule(schedule_hash)
      to_remove = (get_all_schedules || {}).keys - schedule_hash.keys

      schedule_hash.each do |name, job_spec|
        set_schedule(name, job_spec)
      end

      to_remove.each do |name|
        remove_schedule(name)
      end

      @schedule = schedule_hash
    end

The schedules are removed after they are added to the redis. It happens alternatively because the second time they are cleared making the way for third start to set it properly. If this is the correct approach then i am assuming the schedules should have been properly cleared when the sidekiq exited. 

Can you please point out if this issue is genuine or if my understanding is wrong.

Thanks,
Vikram

**Comment by snmgian** [comment]
Hello,

Which versions of `sidekiq` and `sidekiq-scheduler` are you using?

I just setup a sample project and couldn't see the problem you are facing in.

In the UI's navigation bar there are two entries: `Scheduled` and `Recurring Jobs`. The code you are referring to affects the information displayed at `Recurring Jobs`.

As far as I can tell from skimming through the code base, the removed schedules are the ones who are not present in `schedule_hash`, so if a schedule is added, it will not be removed in the next step.

**Comment by vikramcp** [comment]
Hi,

I looked through the code and my configuration and found the issue. The issue was in schedule config in sidekiq.yml. When there was an extra colon before the first entry schedule key(maintenance) it was coming in as symbol from prepare_schedule method and get_all_schedules method was giving keys with string so the array subtraction failed and the key was removed immediately after it was added.

**sidekiq.yml (before fix)**

  :schedule:
      :maintenance:
         cron: '0 */1 * * *'
         class: InactiveScheduler
         queue: inactive_queue
         description: "Queues job to handle inactive objects"

**sidekiq.yml (after fix) -> **
  :schedule:
      maintenance:
         cron: '0 */1 * * *'
         class: InactiveScheduler
         queue: inactive_queue
         description: "Queues job to handle inactive objects"

After removing the extra colon before the "maintenance" key it worked fine.

**Comment by snmgian** [comment]
Good to hear that you solve it by changing your configuration, but definitively it's a misbehaviuor. 

I just found the reason of the failure and opened issue #102 to handle this case, thanks!
