### ISSUE TITLE
Sidekiq::Scheduler.schedules

### ISSUE THREAD

**Issue by sahilchopra** [moove-it/sidekiq-scheduler#122]
Hi 

I am using 
gem 'rails', '4.2.6'
gem 'sidekiq', '4.1.1'
gem 'sidekiq-scheduler', '~> 2.0'

I am trying to see all the schedules jobs.

Sidekiq::Scheduler.schedules
NoMethodError: undefined method `schedules' for Sidekiq::Scheduler:Class
Did you mean?  scheduled_jobs
	from (irb):23
	from/.rvm/gems/ruby-2.3.0@wms/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from .rvm/gems/ruby-2.3.0@wms/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from .rvm/gems/ruby-2.3.0@wms/gems/railties-

**Comment by snmgian** [comment]
Hi @sahilchopra ,

Use `Sidekiq.get_all_schedules` for that. It returns a Hash containing the schedules configuration

**Comment by sahilchopra** [comment]
Thnx
