### ISSUE TITLE
Remove / Stop / dequeue / Unschedule a cron job ?

### ISSUE THREAD

**Issue by syedali90** [moove-it/sidekiq-scheduler#123]
how to do it via code ? not tasking about via web page .. but which method to call for this stuff ?

**Comment by snmgian** [comment]
Hello @syedali90 

Suppose you have two scheduled workers:

``` ruby
schedules = Sidekiq.get_all_schedules
# => {
"high_freq"=>
  {"cron"=>"0 * * * * *", "class"=>"HighFreqWorker", "queue"=>"worker", "description"=>"low"}, 
"low_freq"=>
  {"cron"=>"0 */2 * * * *", "class"=>"LowFreqWorker", "queue"=>"worker", "description"=>"high"}}
```
To unschedule `high_freq` you can try the following:

``` ruby
schedules = schedules.reject { |k, v| k == 'high_freq' }
Sidekiq.schedule = schedules
```

Also, there's another hacky way to achieve the same effect:

``` ruby
Sidekiq.set_schedule('high_freq', { noop: nil })
```

In both cases, the `dynamic` flag must be set to `true`

**Comment by syedali90** [comment]
thanks for detailed reply :)
