### ISSUE TITLE
"Enqueue now" in the web interface not working when the job is not defined within the same project

### ISSUE THREAD

**Issue by bbozo** [moove-it/sidekiq-scheduler#128]
Microservices bla bla bla :) I've got an Admin application which is a Rails app with ActiveAdmin and a Member application which does the actual heavy lifting of the website which is a [Roda app](http://roda.jeremyevans.net/).

The roda app is also the one with all the sidekiq jobs defined and that is the app that defines the schedules - it's beautiful to work with, simple, no-bloat, responses in under 40ms, just.. beautiful  <3

Unfortunately, the sidekiq-scheduler web interface assigned to the rails app expects to find all of the worker classes present locally. Good news is that it seems that the scheduler data in `sidekiq-scheduler` seems to already be in a format that can be used by Sidekiq directly via Redis (see [How do I push a Job to Sidekiq without ruby](https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-push-a-job-to-sidekiq-without-ruby)

Is there an interest to set this up? If so, I'd be interested in giving it a go

**Comment by bbozo** [comment]
It seems this should kind of work already if `Sidekiq::Client.push` will allow it (and if not then Redis connection could be used directly), there's just one breaking point as far as I can see, here:

https://github.com/moove-it/sidekiq-scheduler/blob/master/lib/sidekiq/scheduler.rb#L273

the `constantize` here should be moved to the active job part of the code

Borna

**Comment by bbozo** [comment]
For now the workaround is to simply add a empty SideKiq class

``` ruby
module Foo
  module Bar
    class Worker
      include SideKiq::Worker
    end
  end
end
```

**Comment by snmgian** [comment]
Hi @bbozo 

Just made a new release with the fix you proposed. Thanks!

**Comment by bbozo** [comment]
:D THANK YOU :D
