### ISSUE TITLE
I cannot for the life of me figure out how to get a scheduled job to show in the scheduled section of the web interface.

### ISSUE THREAD

**Issue by NullVoxPopuli** [moove-it/sidekiq-scheduler#136]
Not really sure what I'm doing wrong, as I've looked through many of the existing issues / docs.

Anywho, my expectation is that when I define a scheduled job in `scheduler.yml` and `reload_schedule!` that it should show up under the scheduled tab in the web interface.

Here is my scheduler.yml:
```yml
queue_steps:
  # cron: "every: 30s"
  cron: "0 4 * * *"
  class: QueueStepsJob
  queue: daemons
  args:
  description: "Checks steps to see if they need to be emailed"
```

my sidekiq.yml
```yml
:enabled: true
:dynamic: true
:verbose: true
:concurrency: 25
:queues:
  - mailers
  - default
  - daemons
```

my config/initializers/sideqik_scheduler.rb
```ruby
require 'sidekiq/scheduler'
require 'awesome_print'
require 'sidekiq/cli'
require 'sidekiq/web'

puts "Sidekiq.server? is #{Sidekiq.server?.inspect}"
puts "defined?(Rails::Server) is #{defined?(Rails::Server).inspect}"
puts "defined?(Unicorn) is #{defined?(Unicorn).inspect}"

Sidekiq::Scheduler.enabled = true
Sidekiq::Scheduler.dynamic = true

if defined?(Rails::Server) || defined?(Unicorn)
  Sidekiq.configure_server do |config|
    config.on(:startup) do

      # In case we have lots of crons, migrating to this yml might be a good idea
      config = YAML.load_file(File.expand_path('../../scheduler.yml', __FILE__))

      # this print appropriately shows the jsonified config of scheduler.yml
      ap config
      binding.pry
      Sidekiq.schedule = config
      Sidekiq::Scheduler.reload_schedule!

      # I try to add it again manually just to see if *something* happens
      Sidekiq.set_schedule('queue_steps',
        {
          class: 'QueueStepsJob',
          cron: '0 4 * * *',
          queue: 'daemons',
          description: 'puts bye'
        }
      )
    end

  end

  # lazy way to have 'background jobs' in an environment that only allows one process
  # coughherokucough
  Thread.new do
    cli = Sidekiq::CLI.instance
    cli.parse(['-C', './config/sidekiq.yml', '-L', 'log/sidekiq.log'])
    cli.run
  end
else
  Sidekiq::Scheduler.enabled = false
  puts "Sidekiq::Scheduler.enabled is #{Sidekiq::Scheduler.enabled.inspect}"
end


Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == ["sidekiqadmin", ENV['ADMIN_PASSWORD']]
end
```

I also started sidekiq the 'normal' way just to see if something was weird with my threaded approach
```
$ bundle exec sidekiq -C ./config/sidekiq.yml
```

But after that, the scheduled job still didn't show in the UI.

Any help would be much appreciated. Neither the threaded approach, nor the commandline tells me what I'm doing wrong (even when, in the initializer, I comment out the thread.new part, so I can see exceptions -- I currently get no exceptions)

**Comment by snmgian** [comment]
Hi @NullVoxPopuli 

The `Scheduled` tab is for sidekiq scheduled jobs, those are quite different than jobs configured through sidekiq-scheduler.

You should look at 'Recurring Jobs` tab, it's the last one. Here's the url if you are running the UI locally: http://localhost:8080/recurring-jobs

Hope it helps

**Comment by NullVoxPopuli** [comment]
I don't have that URL anywhere, what generates it?

**Comment by cdotta** [comment]
Hi @NullVoxPopuli I am letting you a screen with the page that @snmgian refers.
![screen shot 2016-09-23 at 11](https://cloud.githubusercontent.com/assets/13123813/18789606/f2f901ea-8181-11e6-89f7-e26e75fbea49.png)

**Comment by snmgian** [comment]
Hi @NullVoxPopuli, did you find the job under 'Recurring Jobs' tab?

**Comment by NullVoxPopuli** [comment]
i don't have that tab. i don't have the pro web interface.

**Comment by snmgian** [comment]
It's not part of sidekiq pro. How are you running the web console? 

Take a look at https://github.com/moove-it/sidekiq-scheduler/blob/master/README.md#sidekiq-web-integration

**Comment by NullVoxPopuli** [comment]
ah, looks like i was just missing require 'sidekiq-scheduler/web'

silly me. thanks!

**Comment by snmgian** [comment]
:+1:

**Comment by Michoels** [comment]
For future reference, I had to add this line to the top of `initalizers/sidekiq.rb`:

```ruby
```
