### ISSUE TITLE
a sample sidekiq.yml file

### ISSUE THREAD

**Issue by thg303** [moove-it/sidekiq-scheduler#144]
Took me 45 minutes to figure out how to put different parts together. here is a sample "sidekiq.yml" file, may help some one.

```
:concurrency: 1
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
staging:
  :concurrency: 2
production:
  :concurrency: 10
:queues:
  - default
  - mailers
  - notifier

tasks: &tasks
  NotifierJob:
    # cron: '*/30 * * * *' does not work on ubuntu
    every: ["2s"]
    queue: notifier
    description: 'Send notification mails each night'

:schedule:
  <<: *tasks
```

If you like to put tasks in another file, you have to load it with ```Yaml.load_file``` in sidekiq initializer (for rails it is: **config/initializers/sidekiq.rb**). As far as I googled there is no way to load another file in ```sidekiq.yml``` (or any other YAML file)

**Comment by snmgian** [comment]
Hello @thg303 

Based on the example you provided, a wiki page was created. Please feel free to make any suggestion.

https://github.com/moove-it/sidekiq-scheduler/wiki/Configuration-samples

**Comment by utilityboy** [comment]
@thg303 I'm curious as to why your `cron` string doesn't work on Ubuntu?  Is this a known issue?

**Comment by thg303** [comment]
@utilityboy 
honestly I tried that with docker, based on debian seed and it works fine. scheduling part is not hard to debug. just make sure `redis server` is configured and is working properly, and if it does, go for syslog and check stuff there.
