### ISSUE TITLE
NoMethodError at /sidekiq/recurring-jobs

### ISSUE THREAD

**Issue by nextofsearch** [moove-it/sidekiq-scheduler#149]
Hi,

I am getting an error while setting up web ui:
ruby 1.9.3
rails 3.2.22.5
sidekiq 3.2.1
sidekiq-scheduler 

`2016-10-21 09:01:50 - NoMethodError - undefined method `Hash' for SidekiqScheduler::JobPresenter:Class:
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sidekiq-scheduler-2.0.19/lib/sidekiq-scheduler/job_presenter.rb:57:in `build_collection'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sidekiq-scheduler-2.0.19/lib/sidekiq-scheduler/web.rb:11:in `block in registered'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/deployer/apps/dashboard/shared/bundle/ruby/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
`

**Comment by nextofsearch** [comment]
I've just found out that 2.0.8 works just fine. So some change in 2.0.9 broke the compatibility with old version of sidekiq, I guess.

**Comment by snmgian** [comment]
PR #150

**Comment by snmgian** [comment]
Released 2.0.20
