### ISSUE TITLE
What happens while sidekiq is down

### ISSUE THREAD

**Issue by vddgil** [moove-it/sidekiq-scheduler#154]
Hello,

When we are deploying, we stop sidekiq when we start the deployment process and restart if after. Sometime sidekiq is down for 2-3 minutes (assets compilation, new gems to install, ...). 
If we have a job that should be enqueued in this time frame, what happens ?
I was wondering if the job is enqueued anyway...

Thanks for your response !

Gil

**Comment by snmgian** [comment]
Hi,

That job will not be enqueued. 

What deployment tool are you using? I have capistrano set to restart sidekiq after git checkout, gem installations, and assets compilation steps are made, so sidekiq downtime will be minimal.

**Comment by vddgil** [comment]
Ok, if I understand, even with your method, there is a risk that a job that should have been enqueued has not actually been enqueued because we are restarting sidekiq at that specific moment ?

**Comment by snmgian** [comment]
If you are running one sidekiq instance you'll have that risk. How many of them do you have?

What types of schedules do you have? cron?, every?)

You could have another sidekiq instance while you are restarting, and then shut it down after the restart of the master instance is finished. 

Jobs not being enqueued just could happen, your server can be restarted, your processes can be killed, those things happen :). So, depending on what you need your jobs to do, you can handle that risk by different ways. 

For example, if you have a jobs scheduled every 5 minutes that sends pending emails, it doesn't matter if the previous job wasn't scheduled; in the worst case an email will be waiting 10 minutes to be delivered.

In the other hand, if you have a job that is scheduled once per day and sends a report to some destination, not delivering the report  could be a problem. In that case, you'll have to think how would you handle that if your server is down at the moment in which the job is scheduled. You can have two instances of sidekiq, or, if you can't afford that, you can run the job twice a day and check if the report has been delivered for the current day (just an idea), or just have a handy way to enqueque the job manually just in case the jobs was not enqueued.
