### ISSUE TITLE
Loading queue from Sidekiq options

### ISSUE THREAD

**Issue by cih** [moove-it/sidekiq-scheduler#157]
Would you be open to a PR that checks the worker options to determine the queue name in addition to checking config file and falling back to "default"? If so I would be happy to make this change.

**Comment by snmgian** [comment]
Sure!

Do you plan to handle ActiveJob workers as well? See http://edgeguides.rubyonrails.org/active_job_basics.html#queues

**Comment by cih** [comment]
Cool I'll take a look into this then, yep I'll make sure to handle ActiveJob workers too.
