### ISSUE TITLE
hashwithindifferentaccess causes problems

### ISSUE THREAD

**Issue by giamma13** [moove-it/sidekiq-scheduler#173]
Hi 
I just tried to use your Gem but when its added to by Gemfile.lock it also add
* hashwithindifferentaccess (0.1.1)

And this is causing lots of problems with my rails app

Many failures like this one

```
Failure/Error: params.require(:mission).permit(:type, :name, :event_driven, :recurrent, :points, :description, :internal_description, :hint, :start_date, :end_date, :event_start, :event_end, :attachment, campaign_ids: [], segment_ids: [], actions_attributes: action_permitted)

NoMethodError:
  undefined method `each' for nil:NilClass
# /home/rof/cache/bundler/ruby/2.3.0/gems/hashwithindifferentaccess-0.1.1/lib/hashwithindifferentaccess.rb:7:in `initialize'
# /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/strong_parameters.rb:149:in `initialize'
# /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/strong_parameters.rb:328:in `new'
# /home/rof/cache/bundler/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/strong_parameters.rb:328:in `permit'
# ./app/controllers/admin/missions_controller.rb:405:in `mission_params'
# ./app/controllers/admin/missions_controller.rb:63:in `create'
```

Have you head of this issue ?

**Comment by snmgian** [comment]
Which version of sidekiq-scheduler are you using?

There was some problem with hashwithindifferentaccess in the past, so we
dropped that dependency in favour of hashie.

Could you upgrade the sidekiq-scheduler version?

**Comment by giamma13** [comment]
I am using
* sidekiq-scheduler (2.0.10)

when I did bundle install, that is what I got

probably its related to the version of sidekiq: 
* sidekiq (4.2.9)

and indirectly to rails 4.2

**Comment by snmgian** [comment]
What do you have in your `Gemfile` ? Did you specify sidekiq-scheduler version ?

``` ruby
# Gemfile
gem 'sidekiq-scheduler', '~> 2'
```

Having smth like the above should have installed the latest version (in 2.x range) of the gem at that moment.  If you run `bundle update sidekiq-scheduler` should install the latest version.

**Comment by snmgian** [comment]
hi @giamma13, do you have any news about this?

**Comment by giamma13** [comment]
@snmgian sorry it took me so long to respond
I am just trying now, and unfortunately i have to re-open

This is my Gemfile
- gem 'sidekiq-scheduler', '~> 2'

And this is what I see in Gemfile.lock after i run ```bundle install```
```
    sidekiq-scheduler (2.0.10)
      hashwithindifferentaccess
      multi_json (~> 1)
      redis (~> 3)
      rufus-scheduler (~> 3.1.8)
      sidekiq (>= 3)
      tilt (>= 1.4.0)
```

**Comment by snmgian** [comment]
Yeah, it says is using v 2.0.10. That version depends on`hashwithindifferentaccess`.

Run  `bundle update sidekiq-scheduler` to grab the current version, which doesn't depend on that gem btw.

**Comment by snmgian** [comment]
After updating `sidekiq-scheduler` version you should see smth like this in your `Gemfile.lock`:

```
    sidekiq-scheduler (2.1.3)
      hashie (~> 3.4)
      redis (~> 3)
      rufus-scheduler (~> 3.2)
      sidekiq (>= 3)
      tilt (>= 1.4.0)
```

**Comment by giamma13** [comment]
if i do bundle update i still get 

```
    sidekiq-scheduler (2.0.10)
      hashwithindifferentaccess
      multi_json (~> 1)
      redis (~> 3)
      rufus-scheduler (~> 3.1.8)
      sidekiq (>= 3)
      tilt (>= 1.4.0)
```

if i force 2.1 of your gem, i get an error

```
Bundler could not find compatible versions for gem "hashie":
  In snapshot (Gemfile.lock):
    hashie (= 2.1.2)

  In Gemfile:
    active_rest was resolved to 0.1.23, which depends on
      hashie (~> 2.1)

    newrelic-grape was resolved to 2.0.0, which depends on
      grape was resolved to 0.13.0, which depends on
        hashie (>= 2.1.0)

    omniauth was resolved to 1.2.1, which depends on
      hashie (< 3, >= 1.2)

    sidekiq-scheduler (~> 2.1) was resolved to 2.1.0, which depends on
      hashie (~> 3.4)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

```

**Comment by snmgian** [comment]
We restricted to much version requirement for hashie. Let me loose that and test if things are still ok when using hashie v2. 

I will respond here after doing that.

**Comment by snmgian** [comment]
As you are using an old version of hashie, which its API is not fully compatible with newer versions, I just removed the dependency and implemented the feature. See issue #182 , and PR #183 

Version 2.14 has been released. Run `bundle update sidekiq-scheduler` to update the gem. Please verify that Gemfile.lock lists the appropriate version.
