### ISSUE TITLE
Sidekiq logger not honored

### ISSUE THREAD

**Issue by n-rodriguez** [moove-it/sidekiq-scheduler#184]
Hi!

I write application logs with syslog. To do so I've got this in `config/initializers/sidekiq.rb` :

```ruby
if Rails.env.production?
  Sidekiq.logger = Syslogger.new("rails.worker", nil, Syslog::LOG_LOCAL7)
  Sidekiq.logger.level = Logger::WARN
end
```
and in `config/environments/production.rb` :

```ruby
config.logger = ActiveSupport::TaggedLogging.new(Syslogger.new("rails.web", nil, Syslog::LOG_LOCAL7))
```

However in logs I have :

```
May  9 00:35:00 cloud rails.web[26138]: Enqueued CheckScheduledAlarms (Job ID: 1c0a5b9f-83ad-4da9-8304-2527453f3b9f) to Sidekiq(scheduler)
May  9 00:35:00 cloud rails.web[26138]: Performing CheckScheduledAlarms from Sidekiq(scheduler)
May  9 00:35:00 cloud rails.web[26138]: Alarm Load (1.3ms)  SELECT  "alarms".* FROM "alarms" WHERE "alarms"."deleted_at" IS NULL ORDER BY "alarms"."id" ASC LIMIT $1  [["LIMIT", 1000]]
May  9 00:35:00 cloud rails.web[26138]: Performed CheckScheduledAlarms from Sidekiq(scheduler) in 551.82ms
```

It seems that Sidekiq logger is override by `production.rb` config.

**Comment by snmgian** [comment]
Hi @n-rodriguez 

Those logging messages are not from neither sidekiq-scheduler and sidekiq. 

I think ActiveJob is logging those messages. `Alarm Load ....` messages comes from ActiveRecord (rails), so it seems to me those messages are from Rails, hence, using the logger you configured in `config/environments/production.rb`

As a side note, when you set Sidekiq.logger.level to WARN, you are silencing  most of sidekiq logging messages.

**Comment by n-rodriguez** [comment]
Hi! Thanks for your answer. 

> Those logging messages are not from neither sidekiq-scheduler and sidekiq.
> 
> I think ActiveJob is logging those messages. Alarm Load .... messages comes from ActiveRecord (rails), so it seems to me those messages are from Rails, hence, using the logger you configured in config/environments/production.rb

That's what I eventually thought :)
