### ISSUE TITLE
Scheduler doesn't accept queue names as symbols

### ISSUE THREAD

**Issue by untoldone** [moove-it/sidekiq-scheduler#185]
Currently if a queue is specified by symbol, such as: `sidekiq_options queue: :production`, schedules are seen as disabled. The current code seems to expect strings.

Quick fix would be to add a `.to_s` to
https://github.com/moove-it/sidekiq-scheduler/blob/c8ebc9d803955ee6cdf86a3414fe595f125720ad/lib/sidekiq/scheduler.rb#L68

Sidekiq itself is fine with queues being named by symbols or strings

**Comment by snmgian** [comment]
PR #186

**Comment by snmgian** [comment]
Released v2.1.5
