### ISSUE TITLE
Suggestion: add a option to disable remove existing jobs when initializing

### ISSUE THREAD

**Issue by IvanChou** [moove-it/sidekiq-scheduler#191]
I have two project which use the same redis db and both have sidekiq-scheduler. Let's call them `ProjectA` and `ProjectB`

ProjectA has a scheduler named `project_a_cron_task`

ProjectB has a scheduler named `project_b_cron_task`

When I start ProjectA (sidekiq only), everything is fine, I can find `project_a_cron_task` on sidekiq web page.

Then, I start ProjectB (sidekiq only),  there is only `project_b_cron_task` on the web page, `project_a_cron_task` is disappeared! WHAT HAPPEND?

After reading the sources, I find `Sidekiq#schedule=` will be called everytime when we start/restart a sidekiq with sidekiq-scheduler.

In `#schedule =`

```ruby
    def schedule=(schedule_hash)
      schedule_hash = prepare_schedule(schedule_hash)
      to_remove = get_all_schedules.keys - schedule_hash.keys.map(&:to_s)

      schedule_hash.each do |name, job_spec|
        set_schedule(name, job_spec)
      end

      to_remove.each do |name|
        remove_schedule(name)
      end

      @schedule = schedule_hash
    end
```

The `schedule_hash` is options of current schedules loading from `redis.yml`. When ProjectB starting, it's options of `project_b_cron_task`. 

`get_all_schedules` return existing jobs from Redis, `project_a_cron_task` is contained.

So, `project_a_cron_task` is removed from `schedules` (it's a hash in Redis) and disapperd from web page. 

If you don't set `dynamic: ture`, `project_a_cron_task` still will be ran correctly. (yeah, I can't see it, but it's still here~)

If you set `dynamic: ture`, there will be more complicated, because when :dynamic flag is set to true, schedule changes are loaded every 5 seconds, `remove_schedule` is one of schedule changes.

schedule changes are loaded by `Sidekiq::Scheduler#update_schedule` which uses `spop` from 'schedules_changed'(set) to check what to reload.

**!! SPOP !!**, that means only one instance can load the changes, others don't know what has happend.

After ProjectB starting, 'schedules_changed' has been updated, if

- ProjectA has only one instance and triggers `update_schedule` firstly,  `project_a_cron_task` will be stoped.
- ProjectA has multiple instances, no matter who triggers `update_schedule` firstly, `project_a_cron_task` will still be ran
- ProjectB triggers `update_schedule` firstly, `project_a_cron_task` will still be ran

Did You have confused？ 哈哈哈(hahahahah)~~~

So, I suggest to add a option: `disable_auto_remove` to keep the existing jobs in redis and aviod triggering `schedules_changed` under the special scene.

By the way, we maybe need a delete button on the web page to manage schedules now, just like queues of Sidekiq.

**One more thing**  Using a Set to store `schedules_changed` is unreasonable，DON'T use SPOP any more, it make your application weakly and unpredictably under distributed scene. Sort-Set is a better choice, the same schedules update should be loaded in all of the instances the same. 

----

Please forgive my poor English~ 😂😂

**Comment by IvanChou** [comment]
In fact, I have finished the features, and run it to test in the QA stage of our company

I can't wait to create a PR to commit it, hahah~~

**Comment by snmgian** [comment]
Hi @IvanChou 

As you said, the problem you found can be solved by adding `disable_auto_remove`, but its a fix for that issue, while having to 2 different apps using the same Redis instance can lead to multiple issues (you just spotted one of them)

I think a simpler approach could be, while allowing each app use the same Redis instance, to configure a different namespace for each one of them. You can have smth like this:

```ruby
# some initializer on project A
Sidekiq.configure_server do |config|
 config.redis = { url: 'redis://localhost', namespace: 'project-A' }
end
```

```ruby
# some initializer on project B
Sidekiq.configure_server do |config|
 config.redis = { url: 'redis://localhost', namespace: 'project-B' }
end
```
Thoughts?

Regarding `SPOP` issue, if you have a fix for that, please feel free to push a PR ;)

**Comment by IvanChou** [comment]
Bingo~
namespace is a better way，I am silly, haha~~

And a new suggestion, how about showing last time of a job on web page. It will help us to sure wether the job was ran as we had expected. If sidekiq-scheduler has been not working (by all kinds of causes), we can find that immediately.

**Comment by IvanChou** [comment]
`namespace` cannot work with `ConnectionPool` ...

**Comment by snmgian** [comment]
Hi @IvanChou 

How are you initializing the connection pool ? Take a look at this: https://github.com/mperham/sidekiq/wiki/Using-Redis

By default, sidekiq setups a connection pool. You need to provide your own in some special cases.

**Comment by snmgian** [comment]
Regarding showing last execution time of a job, that's a good enhancement. See #192

**Comment by IvanChou** [comment]
Thank you for reminding me, @snmgian
 
I find I have been some misunderstanding about the connection pool of sidekiq. I always use a pre-built connection pool and don't know sidekiq can setup a connection pool by itself.

😂😂 Thanks again ~
