### ISSUE TITLE
Schedule not loaded since 2.1.6

### ISSUE THREAD

**Issue by EtienneDepaulis** [moove-it/sidekiq-scheduler#198]
Hello guys,

I started using this gem today and at first my jobs did not load properly (rails 5.0 app).
Everything seamed as in the examples so I tried to downgrading the version from 2.1.6 to 2.1.5 and everything started working normally.

It went from:
```
INFO: Loading Schedule
INFO: Schedule empty! Set Sidekiq.schedule
INFO: Schedules Loaded
```

to:

```
INFO: Loading Schedule
INFO: Scheduling HelloWorld {"cron"=>"0 * * * * *", "class"=>"HelloWorld"}
INFO: Schedules Loaded
```
only by changing the version.
I have no clue about the problem yet and just wanted to signal it :)

**Comment by Anupchat** [comment]
+1

**Comment by sid9102** [comment]
Thank you! I've been pulling my hair out over this for hours!

**Comment by snmgian** [comment]
Guys, just fixed and released. Please install version 2.1.7
