### ISSUE TITLE
cron: '0 30 6 * * 1 Europe/Stockholm' This is not working as expected

### ISSUE THREAD

**Issue by shinku15** [moove-it/sidekiq-scheduler#205]

**Comment by snmgian** [comment]
Tried with `cron: '0 36 2 * * 6 Europe/Stockholm'` and got the job run.

That cron line means: run at 02:36:00 AM on Saturdays according to Stockholm. 

Used this site to check: https://www.timeanddate.com/worldclock/sweden/stockholm
