### ISSUE TITLE
error after gem update - zadd schedules_changed raises WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by mateuszkitlas** [moove-it/sidekiq-scheduler#216]
After I updated sidekiq-scheduler I couldn't run it due to redis command error:
`WRONGTYPE Operation against a key holding the wrong kind of value`

I've find out that type of `schedules_changed` changed from `SET` to `ZSET`
I had to run `redis-cli` and execute `del schedules_changed`

**Comment by snmgian** [comment]
Hi @mateuszkitlas 

Published a release, `v2.1.9` that fixes this problem.
