### ISSUE TITLE
Was this code base extracted and synced with the discourse sidekiq scheduler lib?

### ISSUE THREAD

**Issue by nickjj** [moove-it/sidekiq-scheduler#217]
Hi,

Sorry for the open question but I was wondering if you guys took the discourse sidekiq scheduler and then extracted it into its own gem (while syncing it to the current discourse code base), or is this a totally separate project?

If it's not, what provoked you to write your own vs using theirs?

Thanks!

**Comment by snmgian** [comment]
It's a totally separated project. This library is from March 2012, and the original author of this lib is @mjonuschat; while discourse is from Feb 2013

I took a look at Discourse's scheduler, and its approach is different than the approach behind `sidekiq-scheduler`.

So, short-length answer is: It's a totally separated project, older than discourse's source code release.

**Comment by nickjj** [comment]
Given that you glanced at the code base and have a ton of domain knowledge with schedulers do you have a quick pros/cons list of both implementations?

**Comment by snmgian** [comment]
I'll took a deeper look at Discourse's source code first

**Comment by marcelolx** [comment]
@nickjj Do you still want a quick pros/cons list of both implementations? I could take a look on the internals of the projects if it still needed for you.

**Comment by marcelolx** [comment]
I'm closing this issue @nickjj, anything feel free to reopen the issue or open a new one.

**Comment by nickjj** [comment]
Thanks. It might be worth writing up a pros / cons list for future readers but personally I'm neutral on it being written.
