### ISSUE TITLE
Support for redis-rb ~> 4.0

### ISSUE THREAD

**Issue by dwightwatson** [moove-it/sidekiq-scheduler#218]
Will you be looking to add support for the latest version of `redis-rb`? Sidekiq has updated to support the new version and I'm curious if this library intends to provide compatibility.

**Comment by snmgian** [comment]
Yes. I'll do some testing, and will make a release after that.

**Comment by snmgian** [comment]
Hi, `v2.1.10` has been released supporting `redis-rb >= 3, < 5`

**Comment by dwightwatson** [comment]
Awesome, thank you so much - works a charm!
