### ISSUE TITLE
Interval instead every

### ISSUE THREAD

**Issue by sveredyuk** [moove-it/sidekiq-scheduler#221]
I need to start a new job only 3 minutes after previous one was finished. In fact, I need 3 min pause between finish previous and start a next one.

Maybe I wrongly understood in Readme, but `interval` should help me?

Because now I changed `every` to `interval` but seem like nothing has been changed. Jobs with `interval` behaves same as jobs with `every`

**Comment by snmgian** [comment]
In practice. they behave mostly the same.

In your case, when using `interval`, a new job will be pushed into sidekiq 3 minutes after the previous job was *pushed*, not after 3 minutes after the previous job was *finished*.

The purpose of `sidekiq-scheduler` is to push jobs into sidekiq, not to execute them nor keep track of their executions. 

It can be quite confusing to provide both `interval` and `every` types of jobs, the thing is that the library is based on `rufus-scheduler` which provide both ...

**Comment by sveredyuk** [comment]
@snmgian Thx a lot
