### ISSUE TITLE
Sidekiq5 UI menu missing

### ISSUE THREAD

**Issue by sveredyuk** [moove-it/sidekiq-scheduler#225]
Using this lib in two projects, with sidekiq4 everything is well, but for sidekiq5 UI's it doesn't add any UI elements.

**Comment by snmgian** [comment]
Hi @sveredyuk 

Which versions are you using?

I tested it with sidekiq-scheduler `v2.1.7`, and `v2.1.10`, sidekiq `v5.0.4` and `v5.0.5`.

Here's `config.ru` file:

```ruby
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

run Sidekiq::Web
```

**Comment by sveredyuk** [comment]
Hi, @snmgian. Already found an issue on project side. Thx for attention and sorry for disturb.
