### ISSUE TITLE
Wont Run in Production only in Development

### ISSUE THREAD

**Issue by ronval** [moove-it/sidekiq-scheduler#232]
Hi guys I hope I can get some help. I have added the sidekiq-scheduler gem it was working fine in production until I changed the schedule from 1 day to 2 days. Now it seems to be stuck. It does not run anymore. Im not sure what is happening. I added the enable true which was missing before but the docs say that its set to true by default. I have restarted the workers and I can see that they are started and that they are scheduled but nothing happens. You can see my settings below. Thanks

`2017-12-14T04:22:16.729284+00:00 heroku[worker.1]: Starting process with command `bundle exec sidekiq -e production -C config/sidekiq.yml`
2017-12-14T04:22:17.458493+00:00 heroku[worker.1]: State changed from starting to up
2017-12-14T04:22:25.469203+00:00 app[worker.1]: 4 TID-ou1q16mms INFO: See LICENSE and the LGPL-3.0 for licensing details.
2017-12-14T04:22:25.469204+00:00 app[worker.1]: 4 TID-ou1q16mms INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2017-12-14T04:22:25.469997+00:00 app[worker.1]: 4 TID-ou1q16mms INFO: Booting Sidekiq 5.0.0 with redis options {:url=>"redis://redistogo:REDACTED@koi.redistogo.com:11606/"}
2017-12-14T04:22:25.500596+00:00 app[worker.1]: 4 TID-ou1q16mms INFO: Loading Schedule
2017-12-14T04:22:25.500603+00:00 app[worker.1]: 4 TID-ou1q16mms INFO: Scheduling reminder_queue {"every"=>["2d"], "class"=>"ReminderQueueWorker", "queue"=>"default"}
2017-12-14T04:22:25.503927+00:00 app[worker.1]: 4 TID-ou1q16mms INFO: Schedules Loaded
2017-12-14T04:22:25.503974+00:00 app[worker.1]: 4 TID-ou1q16mms INFO: Starting processing, hit Ctrl-C to stop`

`
sidekiq.yml
development:  
  :concurrency: 5
production:  
  :concurrency: 6
:queues:
  - default
:enabled: true
:schedule:
  reminder_queue:
    every: ['2d']
    class: ReminderQueueWorker

sidekiq.rb
require 'sidekiq'

if Rails.env.production?

  Sidekiq.configure_client do |config|
    config.redis = { url: ENV['REDIS_URL'], size: 3 }
  end

end 

procfile
web: bundle exec puma -C config/puma.rb
worker: bundle exec sidekiq -e production -C config/sidekiq.yml
release: rake db:migrate
`

**Comment by ronval** [comment]
Forgot to mention that it works when I force it by click the enqueue now button.

**Comment by snmgian** [comment]
Just tested with a similar configuration, with `every: '2d'`, manually advanced the system's calendar 2 days, and worked as expected.

Please note that if the sidekiq process started at `2017-12-14T04:22:25...+00:00`, the `every` job will be enqueued at `2017-12-16T04:22:25...+00:00`

Btw, could you format the `config/sidekiq.yml` file a bit?

**Comment by ronval** [comment]
Ya its weird cause it works fine on my staging and local but doesn't work on my production server. Its been stuck like that for a while. I changed the schedule multiple times. You can see when it ran last time here. 
[<a href="http://tinypic.com?ref=33kbsqd" target="_blank"><img src="http://i64.tinypic.com/33kbsqd.png" border="0" alt="Image and video hosting by TinyPic"></a>](url)

I have it formatted just copied and pasted the code came out like that lol.
[
<a href="http://tinypic.com?ref=260qycn" target="_blank"><img src="http://i64.tinypic.com/260qycn.png" border="0" alt="Image and video hosting by TinyPic"></a>
](url)

**Comment by ronval** [comment]
It wasnt working but to test it out some more. I added the first_in: '120s' to force it to go faster. I will let you know if it works in 2 days from now so you can close this thanks!

**Comment by snmgian** [comment]
Did the job run 120s after sidekiq started? 

Did you explicitly set the job's queue? Smth like:

```ruby
class SampleJob < ApplicationJob
  queue_as :milestones
  # ...
```

**Comment by ronval** [comment]
Hi thanks for getting back to me! The jobs did run after I added first_in: '120s', The jobs continued to run over the weekend. So it appears to be working now. I guess you have to tell them when they should start and not just how often. Although when I first implemented this gem I added when the jobs should start and it was working, BUT when I changed when the jobs should run from everyday to every 3 days thats when it stopped working. Even when I had it configured to start the first one after 12hrs. Thats why you can see that the last job ran a month ago in the picture I posted. By this time I had already deleted the option of when the job should start. So its working but something did go wrong at some point. Adding when the job should run made something happen I guess.  Not too sure what other feed back I can give you. Thanks again for the awesome gem :)
