### ISSUE TITLE
Every and Cron not working

### ISSUE THREAD

**Issue by miguelmorales95** [moove-it/sidekiq-scheduler#239]
Hello,

I'm pretty new to Ruby on Rails and so I think I missed something but can't seem to figure it out. Everything works great and was easy to follow but I can't seem to get the worker in the Hello World example to go off every 45 seconds. Whenever I start it up, it just keeps spamming Hello World. I have tried using cron instead but nothing seems to work. Any ideas? Thanks!

**Comment by snmgian** [comment]
Hi, a couple of questions first:

1) What do you have in `config/sidekiq.yml`?
2) Are you testing within a Rails app or just a plain ruby app?

**Comment by miguelmorales95** [comment]
My config/sidekiq.yml looks like

`---
:logfile: ./log/sidekiq_development.log
:concurrency: 1
:queues:
  - default


:schedule:
  daily_reminder:
    class: DailyReminderWorker
    queue: default
    description: "Daily reminders of tasks and projects."
    cron: '00 7 * * *'`
And I am testing within a reails app. Thanks!

**Comment by miguelmorales95** [comment]
1. My config/sidekiq.yml looks like
`---
:logfile: ./log/sidekiq_development.log
:concurrency: 1
:queues:
  - default


:schedule:
  daily_reminder:
    class: DailyReminderWorker
    queue: default
    description: "Daily reminders of tasks and projects."
    cron: '00 7 * * *'`
2. I am testing from a rails app.

Thanks!

**Comment by snmgian** [comment]
Just tested out and didn't observe the behaviour you've described ...

When you said:
> Whenever I start it up, it just keeps spamming Hello World

You mean that 'Hello World' is being printed out more than once every 45 seconds ?

What do you have in `DailyReminderWorker` class? 

Are you sure you're not enqueing the job somewhere? Smth like: `DailyReminderWorker.perform_async` ?

**Comment by snmgian** [comment]
Hi @miguelmorales95, do you have any update on this?

**Comment by snmgian** [comment]
I'm closing this, but if you are still experiencing this issue, feel free to comment again and I'll re open it.
