### ISSUE TITLE
The documentation and the latest version of the gem 2.2.2 are inconsistent

### ISSUE THREAD

**Issue by alireza-a** [moove-it/sidekiq-scheduler#255]
The [latest version](https://rubygems.org/gems/sidekiq-scheduler/versions/2.0.8) of `sidekiq-scheduler` (version 2.2.2) was release on May 15.

On May 27 a breaking change was merged into master #238 that adds a class method `instance` to the `SidekiqScheduler::Scheduler` and makes `reload_schedule!` an instance method.

However, since these changes have not been release, the [documentation](https://github.com/moove-it/sidekiq-scheduler/commit/9f90f5c2dc429ffb772d98b9e0511d499ae25c5e?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) is now inconsistent with how the gem works.

Steps to reproduce:
- Just follow the [Load the schedule from a different file](https://github.com/moove-it/sidekiq-scheduler#load-the-schedule-from-a-different-file) in the README

I was wondering when you would be releasing a new version?

**Comment by snmgian** [comment]
Hi,

Released version 3.0.0. Also, added a note and a link to branch `2.2-stable` in README.
