### ISSUE TITLE
Failing silently on start

### ISSUE THREAD

**Issue by katafrakt** [moove-it/sidekiq-scheduler#262]
I was debugging why the jobs are not executed when scheduled, even though logs suggest everything went fine:

```
{"severity":"INFO","message":"Booting Sidekiq 5.0.5 with redis options {:id=>\"Sidekiq-server-PID-12\", :url=>\"[redacted]\"}","@timestamp":"2018-09-04T13:03:31.544Z","@version":"1"}
{"severity":"INFO","message":"Loading Schedule","@timestamp":"2018-09-04T13:03:31.550Z","@version":"1"}
{"severity":"INFO","message":"Scheduling hello_world {\"cron\"=>\"0 * * * * *\", \"class\"=>\"Workers::HelloWorld\", \"queue\"=>\"tokens\"}","@timestamp":"2018-09-04T13:03:31.550Z","@version":"1"}
{"severity":"INFO","message":"Starting processing, hit Ctrl-C to stop","@timestamp":"2018-09-04T13:03:31.552Z","@version":"1"}
```

I noticed two things here after a while:
1. Only test job `HelloWorld` was added, even though schedule file included more jobs
2. There was no `Schedules Loaded` message before `Starting processing`.

After replaying manually what the gem does in the console I managed to get to the root of the problem, which was this error (which was easy to fix after you know it):

```
TZInfo::DataSourceNotFound: No source of timezone data could be found.
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving this error.
```

However, I was a bit surprised that Sidekiq Schedule gave me no hint of this and just died silently. It would be nice if such errors were mentioned in the logs somehow (or even if they caused whole Sidekiq process to fail).

**Comment by snmgian** [comment]
Hi @katafrakt 

Where do you found the `TZInfo::DataSourceNotFound` exception was raised?

I verified that when TZInfo throws that exception, the exception is back propagated, and the process ends.

```
2018-09-26T20:24:12.168Z 30948 TID-owqv2ktaw INFO: Booting Sidekiq 5.2.2 with redis options {:id=>"Sidekiq-server-PID-30948", :url=>nil}
2018-09-26T20:24:12.170Z 30948 TID-owqv2ktaw INFO: Loading Schedule
2018-09-26T20:24:12.170Z 30948 TID-owqv2ktaw INFO: Scheduling hello_world {"cron"=>"*/10 * * * * * UTC", "class"=>"HelloWorld"}
2018-09-26T20:24:12.171Z 30948 TID-owqv2ktaw WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup"}
2018-09-26T20:24:12.171Z 30948 TID-owqv2ktaw WARN: TZInfo::DataSourceNotFound: No source of timezone data could be found.
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving this error.
```

Could you post the versions of the following gems?

- rufus-scheduler
- et-orbi
- tzinfo

Thanks

**Comment by katafrakt** [comment]
just as a comment, since it was closed anyway. I'm currently unable to reproduce the problem. When there is no tzinfo gem installed I see the error message. The problem must have been specific to our particular and closing is ok.
