### ISSUE TITLE
quiet lifecycle event on sidekiq-scheduler

### ISSUE THREAD

**Issue by dotneet** [moove-it/sidekiq-scheduler#264]
A quiet lifecycle event is fired when a sidekiq process received TSTP signal.
The event notify that the managers of sidekiq process should not  execute more jobs.
But currently sidekiq-scheduler continues executing commands after the event is fired.
I think that sidekiq-scheduler should handle quiet event and stop executing commands anymore after received the event.
Is there any idea about this?

**Comment by snmgian** [comment]
Merged #266
