### ISSUE TITLE
Changing interval at runtime

### ISSUE THREAD

**Issue by sterankin** [moove-it/sidekiq-scheduler#290]
I set up my jobs for a regular schedule, but sometimes this schedule has to change.
It would be nice if we could change the schedule via the front end sidekiq UI in the recurring jobs tab.

So if I needed to change this job:

0 2 * * * America/New_York

I could edit it inline and "Save" it without having to redeploy the application.

I thought this is what the docs meant by dynamic schedules but I couldn't get this to work by adding the :dynamic: to the sidekiq.yml.

Any thoughts on this?

**Comment by AlexeyKatser** [comment]
Same problem.
When I change or add job on runtime its addes or changes its parameters but not INTERVAL.
