### ISSUE TITLE
Unusable on Ruby 2.7.0 because of thwait and e2mmap being missing

### ISSUE THREAD

**Issue by prutya** [moove-it/sidekiq-scheduler#298]
From https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/

```
The following libraries are no longer bundled gems. Install corresponding gems to use these features.
CMath (cmath gem)
Scanf (scanf gem)
Shell (shell gem)
Synchronizer (sync gem)
ThreadsWait (thwait gem) 
E2MM (e2mmap gem)
```

`thwait` is required [here](https://github.com/moove-it/sidekiq-scheduler/blob/40171c14b398d639aee550466a7e927970275c34/lib/sidekiq-scheduler/scheduler.rb#L2)
and looks like it wants `e2mmap` to function

**Comment by shlima** [comment]
+1 here

**Comment by jaynetics** [comment]
see #299

temporary workaround: add the missing dependencies to your `Gemfile`.
```
gem 'e2mmap'
gem 'thwait'
```

**Comment by tarellel** [comment]
I'm working on a new gem (not sidekiq related) and as soon as I tested it with `2.7` and several things broke to get around this I added the following snip to my generated Gemfile.

```ruby
# Gems required for running several rails components with RUBY_VERSION >= 2.7
if RUBY_VERSION >= '2.7'
  gem 'e2mmap'
  gem 'thwait'
end
```

**Comment by dwightwatson** [comment]
Should remain open.

**Comment by dwightwatson** [comment]
...thanks bot

**Comment by marcelolx** [comment]
@dwightwatson I think this problem already was resolved with https://github.com/moove-it/sidekiq-scheduler/pull/299, right?

**Comment by dwightwatson** [comment]
Yeah, this looks good now.
