### ISSUE TITLE
Question . Testing schedules in a rails application

### ISSUE THREAD

**Issue by kigsmtua** [moove-it/sidekiq-scheduler#300]
I am trying to write up a unit tests for validating the schedule set for given jobs
So far what I have is as below:
```ruby 
SidekiqScheduler::Scheduler.instance.reload_schedule!
expect(Sidekiq.get_schedule("job")['cron']).to eql ("0 4 * * *")
expect(Sidekiq.get_schedule("job")['queue']).to eql ("default")
```

Which fails as the schedules are not getting loaded to Redis during the test execution.
Is there a way to actually load the schedules during test execution

**Comment by richrace** [comment]
See here https://github.com/LBHackney-IT/lbh-income-api/pull/351/commits/26d8946154d3c3905a334cf7a59377bcd8b9a9fe for an example of how to load in the Schedule and run some tests.

**Comment by kigsmtua** [comment]
@richrace thank you that works.

**Comment by StanisLove** [comment]
@richrace @kigsmtua 

Could you show the approach? The link is already dead

**Comment by richrace** [comment]
Blast from the past. It was something like this:

```ruby
require 'rails_helper'

 describe 'Scheduling' do
   let(:schedule) { Sidekiq.get_schedule('schedule') }

   before do
     Dir['lib/schedules/*.rb'].each { |file| require file.gsub('lib/', '') }

     Sidekiq.schedule = YAML.load_file('./schedule.yml')
   end

   it 'loads all the class names' do
     schedule.each do |cron_job_name, options|
       next if cron_job_name == 'class'
       expect { options['class'].constantize }.not_to raise_error
     end
   end
 end
```
