### ISSUE TITLE
Warning when using with Ruby 2.7: "URI.escape is obsolete"

### ISSUE THREAD

**Issue by jasonrudolph** [moove-it/sidekiq-scheduler#313]
When using sidekiq-scheduler's [Sidekiq Web integration](https://github.com/moove-it/sidekiq-scheduler/tree/41990aafa80a0f458e988733189fbf4b07e0894a#sidekiq-web-integration) with Ruby 2.7, the sidekiq-scheduler ERB template triggers warnings on two lines:

```
09:31:19 web.1                | (erb):37: warning: URI.escape is obsolete
09:31:19 web.1                | (erb):40: warning: URI.escape is obsolete
```

The referenced lines are:

https://github.com/moove-it/sidekiq-scheduler/blob/41990aafa80a0f458e988733189fbf4b07e0894a/web/views/recurring_jobs.erb#L37

https://github.com/moove-it/sidekiq-scheduler/blob/41990aafa80a0f458e988733189fbf4b07e0894a/web/views/recurring_jobs.erb#L40

In case it helps, these are the specific versions where I'm observing this behavior:

```
$ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

$ bundle info sidekiq-scheduler
  * sidekiq-scheduler (3.0.1)
	Summary: Light weight job scheduling extension for Sidekiq
	Homepage: https://moove-it.github.io/sidekiq-scheduler/
	Path: .rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sidekiq-scheduler-3.0.1
```

**Comment by K1N5L4Y3R** [comment]
I'm also experiencing this when using `require 'sidekiq-scheduler/web'` and navigating to to `/sidekiq/recurring-jobs`.

From what I remember it's as simple as using `CGI.escape` instead of `URI.escape`, if anyone's up for it.

**Comment by marcelolx** [comment]
@K1N5L4Y3R This is already fixed in the latest release of sidekiq-scheduler
