### ISSUE TITLE
Thank you for this gem! I see that you are a little behind. Do you need any help?

### ISSUE THREAD

**Issue by coderberry** [moove-it/sidekiq-scheduler#315]
Hi team,

I first want to thank you for providing this amazing gem! I noticed that there are some deprecation warnings that come with Ruby 2.7 and the latest Sidekiq. I was wondering if you need any help with these?

Thanks!

Eric

**Comment by iax7** [comment]
There is a pull request open, https://github.com/moove-it/sidekiq-scheduler/pull/306 but is stale as this issue.

**Comment by sandstrom** [comment]
Have you considered adding more maintainers to this gem? Maybe you could ask some of the previous contributors (or someone who has provided one of the currently pending PRs and seems skilled) if they want to help out?


CC @gian-zas @gian-zas

**Comment by nepalez** [comment]
Hey guys! Sorry for delay with an answer
For now I really have neither time or energy to support the beast
So if somebody wishes to participate in the support, you're welcome

**Comment by marcelolx** [comment]
Hello guys! I'll give support for this project to keep the gem updated and support new ruby versions.

Support to ruby 3 has already been added, if someone of you needs it ASAP please link to the master branch on your gemfile, I'll be testing the changes on our projects for some days to keep sure there is nothing broken and then we will ship a new release.
