### ISSUE TITLE
How can I only schedule when RAILS_ENV = production instead of all environments?

### ISSUE THREAD

**Issue by thanhtoan1196** [moove-it/sidekiq-scheduler#318]
How can I only schedule when RAILS_ENV = production instead of all environments?

**Comment by bpo** [comment]
@thanhtoan1196 one option is to use a separate scheduling file for each environment. For example in a Sidekiq initializer:

```
Sidekiq.schedule = YAML.load_file(Rails.root.join("config/scheduler/#{Rails.env}.yml"))
```
