### ISSUE TITLE
Run scheduler only for production

### ISSUE THREAD

**Issue by tomaszwojcik** [moove-it/sidekiq-scheduler#321]
I'm trying to run the scheduler in the production environment only, however it seems to work in any environment. I've tried disabling scheduler using `SidekiqScheduler::Scheduler.instance.enabled` but it doesn't seem to work (below you will find my config files).

When Sidekiq starts it states that it runs in the `development` environment, however it still loads the schedule.

```
# initializers/sidekiq.rb
Sidekiq.configure_server do |config|
  config.on(:startup) do
    SidekiqScheduler::Scheduler.instance.enabled = Rails.env.production?
  end
end
```

```
# sidekiq.yml

:concurrency: 10
production:
  :concurrency: 10
:queues:
  - default
:limits:
  tim_integration: 5
:schedule:
  # Warehouses tasks
  grodno_update_stocks:
    cron: '0 3-23 * * *'
    class: Grodno::Inventory::UpdateStocksWorker
```

**Comment by bpo** [comment]
@tomaszwojcik I'm not sure how to do this with the schedule embedded in `sidekiq.yml`, but we achieve this by using a separate yml schedule for each environment, some of which may be blank:

```ruby
  config.on(:startup) do
    Sidekiq.schedule = YAML.load_file(Rails.root.join("config/scheduler/#{Rails.env}.yml"))
    SidekiqScheduler::Scheduler.instance.reload_schedule!
  end
```

If you use this approach, move the contents of the `schedule` block from `sidekiq.yml` to `config/scheduler/production.yml`. You could either create empty schedules for the other environments or add a guard close to prevent error on file load.

**Comment by tomaszwojcik** [comment]
@bpo Seems to work, also good idea to separate them! Thanks!
