### ISSUE TITLE
NoMethodError on Ruby 3.0

### ISSUE THREAD

**Issue by damireh** [moove-it/sidekiq-scheduler#323]
The `URI.escape` method has been made obsolete and is raising a `NoMethodError` on Ruby 3.0

here https://github.com/moove-it/sidekiq-scheduler/blob/master/web/views/recurring_jobs.erb#L37 and https://github.com/moove-it/sidekiq-scheduler/blob/master/web/views/recurring_jobs.erb#L40

> This method is obsolete and should not be used. Instead, use CGI.escape, URI.encode_www_form or URI.encode_www_form_component depending on your specific use case.
> https://ruby-doc.org/stdlib-2.4.1/libdoc/uri/rdoc/URI/Escape.html

**Comment by dennyf** [comment]
Thanks for the pull request, hope to see this fix released soon!
I really needed this to be fixed, so I've implemented a temporary solution by monkey patching the `URI.escape` method to use `encode_www_form_component` for the schedule names only:
```ruby
def self.escape(value)
  if %w[schedule_name_one schedule_name_two].include?(value)
    encode_www_form_component(value)
  else
    super
  end
end
```
