### ISSUE TITLE
Trouble getting Sidekiq-scheduler to work as expected in Rails 5

### ISSUE THREAD

**Issue by hydenp** [moove-it/sidekiq-scheduler#349]
Hi There, I've gotten Sidekiq to work as expected, however I am running into trouble getting Sidekiq Scheduler to work in my rials 5 application. I have the following 

in `my sidekiq.yml`
```
:concurrency: 5

:queues:
  - ["client", 5]
  - ["backend", 1]


:dynamic: true

:schedule:
  test_worker:
    cron: "* * * * *"
    class: TestWorker
```

in my 'config/initializers/sidekiq.rb'
```
url = "redis://localhost:6379/0"
  Sidekiq.configure_server do |config|
    config.redis = { :url => url}
  end
```
and my test_worker.rb
```
require 'sidekiq-scheduler'

class TestWorker
  include Sidekiq::Worker
  sidekiq_options retry: false, queue: 'backend'

  def perform
    (1..2).step(1) do |n|
      sleep(0.5)
      puts "#{n}. Foo "
    end
  end
end
```

I'm running `bundle exec sidekiq -C config/sidekiq.yml` to start the sidekiq service in my terminal from the root of my rails app and it runs fine. I can queue jobs via the rails console but the schedule doesn't seem to be working or loading workers into the queue. When I exit sidekiq with control+c, one of the lines is
`2021-08-10T16:22:11.087Z 23344 TID-ov9bk1roc INFO: Scheduler exiting...`
so it seems as though something is loading/working. However my test worker is not loaded into the queue somehow.

Any help is appreciated!

**Comment by marcelolx** [comment]
Hi @hydenp, did you try to load the schedule from a different file? Something like what is described here https://github.com/moove-it/sidekiq-scheduler#load-the-schedule-from-a-different-file

**Comment by hydenp** [comment]
I've gotten it working now. Beginners error :)

**Comment by marcelolx** [comment]
@hydenp I was answering you right now 😅 Could you share what was the mistake you made? Can be useful for someone else in the future.

And happy to see you made it work 👏

**Comment by hydenp** [comment]
Don't just `gem install sidekiq-scheduler`, also add it to your Gemfile :p
