### ISSUE TITLE
Jobs duplication

### ISSUE THREAD

**Issue by rishm069** [moove-it/sidekiq-scheduler#351]
Hello, I've checked several previous issues related to jobs' duplication but my questions are somewhat different:

I've noticed that when I'm running sidekiq with sidekiq-scheduler on multiple hosts and sidekiq processes are started at different time (say on host-1 it's **00:01:02** and on host-2 it's **00:02:54**), all jobs from my schedule are being duplicated (two hosts => twice as many jobs etc.). 

Here is how I reproduce this:
```
#main.rb
require 'sidekiq-scheduler'

Sidekiq.configure_server do |config|
    config.redis = { url: 'redis://localhost:6379' }
  end
  
Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://localhost:6379' }
end

Dir[File.expand_path('../lib/workers/*.rb',__FILE__)].each do |file| load file; end
```
```
#config/sidekiq.yaml

:schedule:
  hello_world:
    every: 10 seconds
    class: HelloWorld
  bye_world:
    every: 10 seconds
    class: ByeWorld
```
I run it with this command: `sidekiq -r ./main.rb -C ./config/sidekiq.yml`

As mentioned [here](https://github.com/moove-it/sidekiq-scheduler/blob/master/lib/sidekiq-scheduler/scheduler.rb#L134-L151), the scheduler pushes the job into Sidekiq if not already pushed for the given time. The given time is the same second, from what I understand.

Thus, I have a few questions:

1. Is there any suggested way to avoid such duplication?
2. Is it possible to configure the scheduler to check if job has already been pushed disregarding the time (i.e. push only single specific job at any time)?
3. Is it possible to configure time precision for pushing the jobs (e.g. don not push if job has been pushed within past 10 minutes, not 1 second)?

Thanks in advance!

**Comment by rishm069** [comment]
it looks like [this](https://github.com/moove-it/sidekiq-scheduler/issues/88#issuecomment-205640498) answers my questions, mostly

**Comment by arg** [comment]
@rishm069 I think it happens because you're using `every` syntax. As per documentation

> Under normal conditions, `cron` and `at` jobs are pushed once regardless of the number of sidekiq-scheduler running instances, assumming that time deltas between hosts is less than 24 hours.
> ...
> `every`, `interval` and `in` jobs will be pushed once per host.

**Comment by rishm069** [comment]
@arg yes, that's indeed the case here
