### ISSUE TITLE
Use environment variables to pass as arguments in the sidekiq_scheduler file

### ISSUE THREAD

**Issue by camiloabrilth1999** [moove-it/sidekiq-scheduler#360]
Hi, I would like to pass environment variables in the config/sidekiq_scheduler.yml file. 
I have already tried with <%= ENV.fetch('NAME') %> and <%= ENV['NAME'] %> but they are received as strings.
Thanks!

**Comment by marcelolx** [comment]
@camiloabrilth1999 Could you explain more what you're trying to achieve? Maybe with an example app?

What I can tell you is that the schedule config YML file is intended to have just defined the job you want to run and when you want to run it, not to run arbitrary Ruby code.

If your jobs needs to know a value of a given environment variable you can just read it in the job/worker itself.

**Comment by camiloabrilth1999** [comment]
I already solved it @marcelolx  the problem I had was that I wanted to use an environment variable inside the sidekiq_scheduler file...
I was using ruby syntax inside the YML but you have to use their own syntax.

It is done with:
${VAR:default_value}

Then you can call it like this: ${NAME_ENV}

https://www.elastic.co/guide/en/beats/winlogbeat/current/using-environ-vars.html
