### ISSUE TITLE
CSS no longer loads on Rails app with Asset Pipeline or Webpack

### ISSUE THREAD

**Issue by jbrodie** [moove-it/sidekiq-scheduler#364]
With the recent changes that were done with moving the styling to its own file, the file is not being loaded within a Rails application using asset pipeline or webpack.

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/609124/156789753-08617a88-2f8c-4c03-9139-503fb547a991.png">

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/609124/156789894-a09d9297-d807-4eb1-b9d2-321c63239d7e.png">

As a work around, I have locked the gemfile at the commit before the change that moved the styling to a stand alone file.
`gem 'sidekiq-scheduler', git: 'https://github.com/moove-it/sidekiq-scheduler.git', ref: '00b8459c728dfb866c1fa424377f9c69d0080ded'
`

**Comment by marcelolx** [comment]
@jbrodie Can you please provide a sample project to make it easier for me to simulate this problem you're having? Thank you!

**Comment by manuelmeurer** [comment]
I'm having the same problem.
@marcelolx Do you not have the problem with a default Sidekiq setup with the latest version of `sidekiq-scheduler`?

**Comment by bpo** [comment]
I have apps using the v7 asset pipeline and one of the webpack v6 RCs. Neither had this issue with the master branch of sidekiq-scheduler. There should probably be an associated stacktrace in the Rails logs from the 500 error on the server. If so can you share? @manuelmeurer @jbrodie

**Comment by manuelmeurer** [comment]
It causes a 500 because the path "/sidekiq/stylesheets/recurring_jobs.css" triggers a "ActionController::RoutingError" instead of a 404.
I'm using sidekiq-scheduler 3.1.1 on Rails 6.1 and Webpack 4.

@bpo Is the file /sidekiq/stylesheets/recurring_jobs.css successfully loaded in your apps, or does sidekiq-scheduler not try to load it?

**Comment by bpo** [comment]
@manuelmeurer it gets loaded successfully via propshaft with Rails 7 and master.

**Comment by manuelmeurer** [comment]
Ok, I think I found the issue. I am using Sidekiq 5 in my project, when I upgrade to Sidekiq 6, the CSS file is loaded successfully.
So I guess it's a question whether sidekiq-scheduler aims to support Sidekiq 5 as well. 😄 
IMO it's not absolutely necessary.

**Comment by marcelolx** [comment]
@manuelmeurer Mind testing https://github.com/moove-it/sidekiq-scheduler/pull/377? I've tested locally and now it works with both sidekiq 5 and 6.

I'll cherry-pick those changes to v3-stable once merged.

**Comment by marcelolx** [comment]
v3.2.1 released https://github.com/moove-it/sidekiq-scheduler/releases/tag/v3.2.1

**Comment by manuelmeurer** [comment]
@marcelolx Sorry, I didn't get around to testing #377 yet... would that still be useful or did you manage to test it yourself?

**Comment by marcelolx** [comment]
@manuelmeurer Yes I did test it; I had already tested it before I asked you to test it, I just did want to make sure it would be fixed for you too, but no worries, I'm sure if something got broken someone will open a new issue!

Thank you all!
