### ISSUE TITLE
Unused dependencies?

### ISSUE THREAD

**Issue by jasonpenny** [moove-it/sidekiq-scheduler#365]
https://github.com/moove-it/sidekiq-scheduler/blob/eb013561ac1d65540296d5f69eb38142761ca058/sidekiq-scheduler.gemspec#L21-L22

`thwait` and `e2mmap` are marked as dependencies, but they don't appear to be used in this gem.

Can they be removed?

**Comment by marcelolx** [comment]
hey @jasonpenny, I'll investigate, and if not used they will be removed in v4.

Thanks for your report!

**Comment by marcelolx** [comment]
Hey @jasonpenny, can you test with the branch of the PR https://github.com/moove-it/sidekiq-scheduler/pull/371 to see if sidekiq-scheduler keeps working as expected?

**Comment by jasonpenny** [comment]
Yes, it appears to continue working and these gems were removed from `Gemfile.lock` when I updated to that branch

**Comment by marcelolx** [comment]
Nice! Thank you for testing it! ❤️
