### ISSUE TITLE
Warning: Redis Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0

### ISSUE THREAD

**Issue by Robeeerto** [moove-it/sidekiq-scheduler#366]
Ruby version: 2.7.5
Rails version:  6.1.4.7
Sidekiq version: 6.4.1

Got this warning from Redis

```
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

redis.multi do
  redis.get("key")
end

should be replaced by

redis.multi do |pipeline|
  pipeline.get("key")
end

(called from /Users/RobertChang/.rvm/gems/ruby-2.7.5/gems/sidekiq-scheduler-3.1.1/lib/sidekiq-scheduler/redis_manager.rb:140:in `block in register_job_instance'}
```

**Comment by marcelolx** [comment]
Has already been fixed in https://github.com/moove-it/sidekiq-scheduler/pull/357

**Comment by natematykiewicz** [comment]
@marcelolx Can you release a new version that includes this fix?

**Comment by marcelolx** [comment]
I did cherry-pick that fix to the v3 branch https://github.com/moove-it/sidekiq-scheduler/tree/v3-stable, please point your Gemfile to that branch. When I have more time I'm gonna release 3.1.2

**Comment by natematykiewicz** [comment]
Thanks!

**Comment by marcelolx** [comment]
3.2.0 released https://rubygems.org/gems/sidekiq-scheduler/versions/3.2.0, changelog https://github.com/moove-it/sidekiq-scheduler/blob/v3-stable/CHANGELOG.md
