### ISSUE TITLE
`config.options[:key] =` is deprecated on Sidekiq 6.5.0

### ISSUE THREAD

**Issue by tagliala** [moove-it/sidekiq-scheduler#384]
Hi,

I'm getting a deprecation message when using sidekiq-scheduler 4.0.1 with Sidekiq 6.5.0:

```
2022-06-08T14:47:01.226Z pid=46635 tid=trz WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["sidekiq-scheduler-4.0.1/lib/sidekiq-scheduler.rb:16:in `block (2 levels) in <main>'", "sidekiq-6.5.0/lib/sidekiq/component.rb:56:in `block in fire_event'"]
```

Ref: mperham/sidekiq@67daa7a408b214d593100f782271ed108686c147

**Comment by couquino** [comment]
Hello, I'm getting the same here.

sidekiq-scheduler 4.0.1 with Sidekiq 6.5.0 too.

**Comment by marcelolx** [comment]
@couquino I'm aware of it, once I have time I'll work on a fix; Please be patient.

**Comment by couquino** [comment]
> @couquino I'm aware of it, once I have time I'll work on a fix; Please be patient.

No problem at all ! It doesn't block anything for our app ;) Good luck fixing it

**Comment by wflanagan** [comment]
FYI, it is for me. had to revert sidekiq to get this working.

**Comment by tagliala** [comment]
I've tried to take a look because I wanted to submit a PR.

As far as I can tell, this is not a trivial change, especially if backward compatibility should be preserved.

Also, specs does not cover the configuration :\

**Comment by t27duck** [comment]
I took a swing at it at https://github.com/moove-it/sidekiq-scheduler/pull/385 (comments include an example repo that appears to show it works?)
