### ISSUE TITLE
Multiple schedules are loaded for multiple workers

### ISSUE THREAD

**Issue by ygoldshtrakh** [moove-it/sidekiq-scheduler#41]
We have an environment where we have multiple worker processes and each of this process loads up the scheudler
ie we have:
scheduler: bundle exec sidekiq -c 5 -q scheduler -q default
worker: bundle exec sidekiq -c 5 -q default

So we end up with duplicate schedules , how can we avoid it?

**Comment by wcurtis** [comment]
+1 

Same issue here, using @jgeggatt's fix for now.

**Comment by artem-russkikh** [comment]
Take a look at https://github.com/itbeaver/sidekiq-scheduler/pull/1

```ruby
# config/initializers/sidekiq_scheduler.rb
require 'sidekiq/scheduler'

puts "Sidekiq.server? is #{Sidekiq.server?.inspect}"
puts "defined?(Rails::Server) is #{defined?(Rails::Server).inspect}"
puts "defined?(Unicorn) is #{defined?(Unicorn).inspect}"

if Rails.env == 'production' && (defined?(Rails::Server) || defined?(Unicorn))
  Sidekiq.schedule = YAML
    .load_file(File.expand_path('../../../config/scheduler.yml', __FILE__))
  Sidekiq::Scheduler.reload_schedule!
else
  Sidekiq::Scheduler.enabled = false
  puts "Sidekiq::Scheduler.enabled is #{Sidekiq::Scheduler.enabled.inspect}"
end
```

I use this gem with Unicorn, him process start sidekiq-scheduler and queue tasks
But sidekiq workers disables it when starting (in initializer)

After writing test I make a Merge Request into this repo
