### ISSUE TITLE
Is it possible to display next run time in web UI?

### ISSUE THREAD

**Issue by andrewhavens** [moove-it/sidekiq-scheduler#84]
I see my recurring jobs schedule in the Sidekiq UI. Even though my schedule is listed, it's still not very clear to me exactly when they will be run. It would be nice to know when the next job is scheduled to run. It would help a lot with debugging.

I'm not familiar with the internals to know how to make this possible. Is it possible to display next run time in web UI?

**Comment by elpic** [comment]
I'm not sure, but I will investigate if it's possible.

**Comment by elpic** [comment]
Sometimes the web server run in a process and sidekiq in other, so sometimes is not possible to get the next run time. I'm making some modifications to try to solve this. 

I will keep investigating this.

**Comment by nengine** [comment]
In my case, scheduled jobs are running fine but cannot see any of them in the Sidekiq UI Scheduled tab.  Not so sure what I'm doing wrong. Thanks.

**Comment by snmgian** [comment]
@nengine Jobs scheduled by sidekiq-scheduler are displayed at `Recurring Jobs` tab. 

The `Scheduled` tab is a view handled by sidekiq for its special type of scheduled jobs, https://github.com/mperham/sidekiq/wiki/Scheduled-Jobs

**Comment by snmgian** [comment]
PR #115 is merged.
