### ISSUE TITLE
respect prior value of Sidekiq::Scheduler.enabled

### ISSUE THREAD

**Issue by kwstannard** [moove-it/sidekiq-scheduler#85]
https://github.com/moove-it/sidekiq-scheduler/commit/d8b66fabb647e808762d4301be9699759df2f007

This changes the logic so that if you explicitly set enabled=false in your initializers it is always overwritten. If enabled was set prior, then it should not be overwritten here.

**Comment by elpic** [comment]
The version v2.0.4 was released, this version is a fix for this issue.
