### ISSUE TITLE
Queue, Enable / Disable in Sidekiq Tab

### ISSUE THREAD

**Issue by jclusso** [moove-it/sidekiq-scheduler#87]
Would be nice to have this functionality that is available in https://github.com/ondrejbartas/sidekiq-cron

We switched away because sidekiq-cron doesn't appear to be working properly with high volume in Sidekiq 4, but this feature was definitely nice so you don't have to redeploy if you just need to disable a scheduled task.

![screen shot 2016-02-11 at 5 08 56 pm](https://cloud.githubusercontent.com/assets/622516/12996166/44fb2fa0-d0e2-11e5-8bc9-8fbc2fe6aa01.png)

**Comment by elpic** [comment]
Ok, I will work on this.

Thank you

**Comment by lucasgomide** [comment]
Add column `Last enqueued` would be wonderful too (:

**Comment by jclusso** [comment]
+1 for the `Last Enqueued` as well!

**Comment by sahilchopra** [comment]
+1

**Comment by snmgian** [comment]
PR #143 is merged into master
