### ISSUE TITLE
Cron job doesn't run

### ISSUE THREAD

**Issue by maxrosecollins** [moove-it/sidekiq-scheduler#89]
Hi,

I'm trying to run a job with the `cron: "0 0 19 * * *"` but it doesn't ever run.

I'f I click the enqueue button on the web interface it runs my job though.

Any ideas where I am going wrong?

**Comment by maxrosecollins** [comment]
any ideas?

**Comment by elpic** [comment]
This will run at 00:00 on the 19th of every month. Is that what you want?

**Comment by maxrosecollins** [comment]
With 6 options doesn't it mean the first is seconds second is minutes and third is hours? So my understanding was 00:00:19 every day every month every year?

**Comment by elpic** [comment]
Yes, you are right. Could you add more info about your configuration and the way you load the scheduler?

Thanks

**Comment by maxrosecollins** [comment]
My `scheduler.yml` file

**Comment by elpic** [comment]
The config startup should be like this:

```
config.on(:startup) do
  Sidekiq.schedule = YAML.load_file(File.expand_path("../../../config/scheduler.yml",__FILE__))
  Sidekiq::Scheduler.load_schedule! # This will retrigger the loading stage 
end
```

But you can also avoid this if you add the :schedule: line to you sidekiq.yml like this

```
:schedule:
  DailyCheckWorker:
    cron: "0 20 00 * * *"
    class: DailyCheckWorker
    queue: worker
    description: "abcdef"
```

**Comment by maxrosecollins** [comment]
Okay, so it is working now. Thank you!

but it seems to trigger the job multiple times?

**Comment by elpic** [comment]
Sorry you should use reload_schedule! instead of load_schedule!

**Comment by maxrosecollins** [comment]
It still runs the job on each queue I have. Do I need to load different sidekiq configs into my queues?
For example...
```
web: bundle exec puma -C config/puma.rb
reports: bundle exec sidekiq -q reports
worker: bundle exec sidekiq -q worker -C ./config/differentsidekiqconfig.rb
```

**Comment by maxrosecollins** [comment]
Sorry I didn't mean to close the issue

**Comment by elpic** [comment]
Is this related with this issue? Because I thought that this issue was related with the fact that the jobs was not running.

**Comment by maxrosecollins** [comment]
Okay I will open a new issue that reflects the new problem
