### ISSUE TITLE
missing tilt dependency

### ISSUE THREAD

**Issue by skippy** [moove-it/sidekiq-scheduler#94]
it was removed here: 

https://github.com/moove-it/sidekiq-scheduler/commit/e173071d8fb6ef7e767fee0d6953c69449c257dd#diff-6706bb7d3bf023a73d5dd7443cb89459L25

but there is still a dependency on tilt in the code base.

**Comment by skippy** [comment]
I actually addressed this in #93

**Comment by elpic** [comment]
Already merged v2.0.5
