### ISSUE TITLE
Drop tilt version dependency

### ISSUE THREAD

**Issue by rj3d** [moove-it/sidekiq-scheduler#97]
We were stuck at sidekiq-scheduler 2.0.0 due to the requirement that tilt be at version 2.0. We're currently using sass-rails 4.0.2, which requires tilt version 1.4.1. Upgrading tilt would require us to upgrade sass-rails, and upgrading sass-rails would require a good amount of effort on our part due to some major changes. As a last ditch effort, we forked the sidekiq-scheduler repo and dropped the tilt version requirement to >= 1.4.0 and pointed our gemfile to our forked repo. The gem installs fine, and, from what I can tell, functions as expected. It seems like you were only using the gem to parse erb files, and the web interface functions perfectly. Was there any reason you had tilt pegged to 2.0? If not, would you mind dropping the version requirement so that we can switch back to the official repo?

Thanks!

**Comment by elpic** [comment]
Sure no problem. Please feel free to upload a PR that way we can release a new version
